### ISSUE TITLE
Date Formatting

### ISSUE THREAD

**Issue by ForkingPaths2040** [ForkingPaths2040/Pointual#1]
# PROJECT ISSUE TICKET

## Unexpected Behavior

> I did a hire_date attribute in my model with a date datatype. I am following Ruby format and getting an error.

## Expected Behavior

> I want the seed data to succeed with the format of date input i give it.

## Reproduce the Error

> Incorrect format, I have tried Postgresql format, Ruby format. 

```
@date1 = Date.new(2020, 12, 20)
@date2 = Date.new(2020, 12, 25)

@employee1 = Employee.create!(
first_name: 'John',
last_name: 'Smith',
points: 0,
email: 'johnsmith@gmail.com',
phone_number: 5551230000,
position: 'Boards',
hire_date: @date1,
tenure: 15)

puts "#{Employee.count} employees created"

@infraction1 = Infraction.create!(attendance: 'tardy', date: @date2, points: 1, reason: 'Late by 3 mins due to waking up late.', employee: @employee1)

puts "#{Infraction.count} infractions created"

```

## Documentation

```
rails aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "application_records" does not exist
LINE 8:  WHERE a.attrelid = '"application_records"'::regclass
                            ^
/Users/hub/Desktop/General_Assembly/projects/Pointual/db/seeds.rb:8:in `<main>'
/Users/hub/Desktop/General_Assembly/projects/Pointual/bin/rails:9:in `<top (required)>'
/Users/hub/Desktop/General_Assembly/projects/Pointual/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
PG::UndefinedTable: ERROR:  relation "application_records" does not exist
LINE 8:  WHERE a.attrelid = '"application_records"'::regclass
                            ^
/Users/hub/Desktop/General_Assembly/projects/Pointual/db/seeds.rb:8:in `<main>'
/Users/hub/Desktop/General_Assembly/projects/Pointual/bin/rails:9:in `<top (required)>'
/Users/hub/Desktop/General_Assembly/projects/Pointual/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

```

## Attempted Resolution

```md
1. https://nandovieira.com/working-with-dates-on-ruby-on-rails
2. https://ruby-doc.org/stdlib-2.6.1/libdoc/date/rdoc/Date.html
```

**Comment by ForkingPaths2040** [comment]
Date was properly formatted. Authentication model was edited when it was suppose to be Authentication controller.
